### ISSUE TITLE
Status of the driver

### ISSUE THREAD

**Issue by stof** [nstojiljkovic/mink-capybara-webkit-driver#1]
Hello,

I'm one of the lead developers of Mink. I would like to know how to consider this driver. Are you actively maintaining it ? In yes, we could link to it in the official doc (creating a new section about third-party drivers) once the driver is updated to be compatible with Mink 1.6 (current stable). I can do a full review of the driver in this case if you want, to help you improving it.

**Comment by nstojiljkovic** [comment]
Hi,

we are actively using it on our project with Mink 1.5 and our little hack package essentialdots/weasel. Don't know if it is possible now to include 3rd party drivers without these kind of hacks, didn't have time to check it recently. We never wrote any tests for it, but it's very stable on our infrastructure.

I won't have time in next few weeks to update as we are close to go live with our startup project, but in perspective, we will maintain this driver and keep it up to date with the latest versions of Behat/Mink/Capybara.

Regards,
Nikola

**Comment by stof** [comment]
@nstojiljkovic in Mink 1.6, we have a driver-testsuite which allows ensuring consistency between drivers by running the same tests each time. This will be one of the benefits of using Mink 1.6

Regarding Weasel, this is about hooking into Behat, not into Mink AFAICT. This is not related to upgrading to Mink 1.6 at all (you would need to update it if you plan migrating to Behat 3 though)
